//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_VietFest_TEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPham
    {
        public int id_sp { get; set; }
        public string ten_sp { get; set; }
        public string image { get; set; }
        public int id_dv { get; set; }
        public int id_dmsp { get; set; }
        public Nullable<int> id_mau_sac { get; set; }
        public Nullable<double> gia { get; set; }
        public string mo_ta { get; set; }
    
        public virtual tblDanhMucSanPham tblDanhMucSanPham { get; set; }
        public virtual tblDonVi tblDonVi { get; set; }
        public virtual tblMauSac tblMauSac { get; set; }
    }
}
