//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_VietFest_TEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThanhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblThanhVien()
        {
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int id_thanh_vien { get; set; }
        public string ten_thanh_vien { get; set; }
        public Nullable<int> ngay_vao_lam { get; set; }
        public Nullable<int> gioi_tinh { get; set; }
        public string mo_ta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
