//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_VietFest_TEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int id_users { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int trang_thai { get; set; }
        public string mo_ta { get; set; }
        public Nullable<int> id_nhan_vien { get; set; }
    
        public virtual tblThanhVien tblThanhVien { get; set; }
    }
}
